remove this line with envrender.sh --rmfirst parameter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME_GENERATED}
  labels:
    app: ${PROJECT_NAME_GENERATED}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME_GENERATED}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME_GENERATED}
    spec:
      containers:
        - name: ${PROJECT_NAME_GENERATED}
          image: "$PROTECTED_DOCKER_REGISTRY/$PROJECT_NAME:$DEPLOYMENT_TAG" # docker run -p 8082:80 docker-registry.domain.com/tapp:0.0.12
          # docker run -it $PROTECTED_DOCKER_REGISTRY/$PROJECT_NAME:$DEPLOYMENT_TAG bash
          ports:
            - containerPort: 80
          env: # g(Expose Pod Information to Containers Through Environment Variables) https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#          #          imagePullPolicy: IfNotPresent
#          # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request
#          livenessProbe:
#            httpGet:
#              # it will ping this endpoint 3 times and if it will 3 times return 404 then it will wait terminationGracePeriodSeconds and restart pod
#              path: /liveness # Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
#              port: http
#            #              httpHeaders:
#            #                - name: Custom-Header
#            #                  value: Awesome
#            initialDelaySeconds: 5 # Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.
#            periodSeconds: 4 # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
#            timeoutSeconds: 1 # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.

          volumeMounts:
#            - name: image-store
#              mountPath: /home/node/app/public/media
            - name: env-secret
              mountPath: /usr/src/envdir
              readOnly: true


            # /usr/src/envdir/.env /home/node/app/.env

      imagePullSecrets:
        - name: regcred
      volumes:
        - name: env-secret
          secret:
            secretName: env-${PROJECT_NAME_SHORT}
#        - name: image-store
#          persistentVolumeClaim:
#            claimName: pvc-${PROJECT_NAME_PVC__NODASH}
#            readOnly: false
      terminationGracePeriodSeconds: 2 # how long to wait for SIGKILL handler to finish before pod will be killed by k8s
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME_GENERATED}-service
spec:
  #  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  #      nodePort: 30010
  selector:
    app: ${PROJECT_NAME_GENERATED}
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: cephfs-lhhub
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 20Gi
#  storageClassName: csi-cephfs
